"""initial app schema

Revision ID: 456b6156babe
Revises: 
Create Date: 2026-06-19 02:24:27.587005
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456b6156babe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('underlying', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('channel', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown_s', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_user_id'), ['user_id'], unique=False)

    op.create_table('behavioral_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_type', sa.String(length=24), nullable=False),
    sa.Column('underlying', sa.String(length=24), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('linked_snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('behavioral_journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavioral_journal_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavioral_journal_user_id'), ['user_id'], unique=False)

    op.create_table('broker_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'broker', name='uq_broker_tokens_user_broker')
    )
    with op.batch_alter_table('broker_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broker_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('live_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.String(length=32), nullable=False),
    sa.Column('underlying', sa.String(length=24), nullable=False),
    sa.Column('created_ts', sa.String(length=40), nullable=False),
    sa.Column('resolve_ts', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('prob', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'forecast_id', name='uq_live_forecasts_user_fid')
    )
    with op.batch_alter_table('live_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_forecasts_underlying'), ['underlying'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_forecasts_user_id'), ['user_id'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('benchmark', sa.String(length=24), nullable=False),
    sa.Column('net_delta', sa.Float(), nullable=False),
    sa.Column('net_gamma', sa.Float(), nullable=False),
    sa.Column('net_theta', sa.Float(), nullable=False),
    sa.Column('net_vega', sa.Float(), nullable=False),
    sa.Column('bw_delta', sa.Float(), nullable=False),
    sa.Column('bwd_lots', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('explain_mode', sa.String(length=16), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('benchmark', sa.String(length=24), nullable=False),
    sa.Column('prefs', sa.JSON(), nullable=False),
    sa.Column('feature_flags', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_user_id'), ['user_id'], unique=False)

    op.create_table('what_changed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('underlying', sa.String(length=24), nullable=False),
    sa.Column('as_of', sa.String(length=10), nullable=False),
    sa.Column('prev_snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'underlying', 'as_of', name='uq_what_changed_user_underlying_asof')
    )
    with op.batch_alter_table('what_changed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_what_changed_user_id'), ['user_id'], unique=False)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('underlying', sa.String(length=24), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_fired_at'), ['fired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_fired_at'))

    op.drop_table('alert_events')
    with op.batch_alter_table('what_changed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_what_changed_user_id'))

    op.drop_table('what_changed')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_user_id'))

    op.drop_table('watchlists')
    op.drop_table('user_profile')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_ts'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('live_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_forecasts_user_id'))
        batch_op.drop_index(batch_op.f('ix_live_forecasts_underlying'))

    op.drop_table('live_forecasts')
    with op.batch_alter_table('broker_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broker_tokens_user_id'))

    op.drop_table('broker_tokens')
    with op.batch_alter_table('behavioral_journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavioral_journal_user_id'))
        batch_op.drop_index(batch_op.f('ix_behavioral_journal_ts'))

    op.drop_table('behavioral_journal')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_user_id'))

    op.drop_table('alert_rules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
